name: 'lourdes-ayala'
services:
  app:
    build: ./app/
    ports:
      - '3000:3000'
    container_name: app
    command: bun --bun run dev
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/
        - action: rebuild
          path: ./app/package.json
  db:
    container_name: db
    image: postgres:alpine
    environment:
      [
        "POSTGRES_USER=dbAdmn",
        "POSTGRES_PASSWORD=LouAyala2024",
        "PGDATA=/var/lib/postgresql/data/pgdata"
      ]
    ports:
      - '3001:5432'
    volumes: [ ./db:/var/lib/postgresql/data ]
